### ISSUE TITLE
Admin user cannot use config page

### ISSUE THREAD

**Issue by pvannierop** [NrgXnat/xnat-docker-compose#37] opened 2020-06-23 14:34 UTC
Overall I experience many issues deploying your docker-compose solution. I encounter:

- Error that causes the database not to initiate as described [here](https://github.com/NrgXnat/xnat-docker-compose/issues/28).
- The ngix proxy not starting (that is at least my diagnosis) as described [here](https://github.com/NrgXnat/xnat-docker-compose/issues/20).

# Problem
To test drive XNAT I have created by own docker compose solution that uses an Apache HTTPD reverse proxy that hosts XNAT at address `https://hostname/xnat`.

When doing this all initialization is fine, but while logging in as admin after first start I encounter session problems. As soon as I log in, immediately a message `User session ended` is shown and I cannot use the config page (see movie below). The page continues to auto-reload every 30 seconds or so.

Do you know what may be the problem here? Do you have suggestions to find the cause?

![Peek 2020-06-23 16-27](https://user-images.githubusercontent.com/745885/85416915-4dd4a400-b56f-11ea-9491-cf31c9020ee0.gif)

# System setup

## Operating system
- Ubuntu 18.04
- Docker version 19.03.11, build 42e35e61f3
- docker-compose version 1.25.4, build 8d51620a

## Apache HTTPD config

Reverse proxy that hosts XNAT at address `https://localhost/xnat`.

```
Listen 80
Listen 443

<VirtualHost *:80>
  ServerName localhost
  Redirect / https://localhost/
</VirtualHost>

<VirtualHost *:443>
  SSLEngine on
  SSLCertificateFile /etc/ssl/cbio_https/cert.crt
  SSLCertificateKeyFile /etc/ssl/cbio_https/key.key
  ServerName localhost

  Header always set Strict-Transport-Security "max-age=15768000"

  ErrorLog /tmp/cbio_https_error.log
  LogLevel warn
  CustomLog /tmp/cbio_https_access.log combined

  ProxyPass /xnat http://xnat:8080/xnat
  ProxyPassReverse /xnat http://xnat:8080/xnat

  ProxyPreserveHost On

  <Location "/">
    AuthType None
    Require all granted
  </Location>

</VirtualHost>
```

## docker compose

The XNAT service is built with `TOMCAT_XNAT_FOLDER` set to `xnat` to support the `https://localhost/xnat` URL pattern.

```
version: '2.4'
networks:
  xnat-net:
    name: xnat-net

services:
  xnat:
    build:
      context: https://github.com/NrgXnat/xnat-docker-compose.git#:xnat
      args:
        XNAT_VER: '1.7.6'
        XNAT_DATASOURCE_DRIVER: 'org.postgresql.Driver'
        XNAT_DATASOURCE_URL: 'jdbc:postgresql://xnat-db/xnat'
        XNAT_DATASOURCE_USERNAME: 'xnat'
        XNAT_DATASOURCE_PASSWORD: 'xnat'
        XNAT_HIBERNATE_DIALECT: 'org.hibernate.dialect.PostgreSQL9Dialect'
        TOMCAT_XNAT_FOLDER: xnat
        XNAT_ROOT: /data/xnat
        XNAT_HOME: /data/xnat/home
    container_name: xnat
    networks:
      - xnat-net
    volumes:
      - ./client/xnat/plugins:/data/xnat/home/plugins
      - ./log/xnat:/data/xnat/home/logs
      - ${XNAT_FILE_DIR:-../xnat_application/}/archive:/data/xnat/archive
      - ${XNAT_FILE_DIR:-../xnat_application/}/build:/data/xnat/build
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - xnat-db
    environment:
      - CATALINA_OPTS=-Xms128m -Xmx2048m -Dxnat.home=/data/xnat/home
      - XNAT_HOME=/data/xnat/home

  xnat-db:
    build:
      context: https://github.com/NrgXnat/xnat-docker-compose.git#:postgres
    container_name: xnatdb
    networks:
      - xnat-net
    volumes:
      - ${XNAT_DATA_DIR:-../xnat_files/}:/var/lib/postgresql/data
    expose:
      - "5432"

  apache-proxy:
    networks:
      - xnat-net
    image: httpd:2.4.29
    container_name: apache-proxy
    restart: always
    volumes:
      - ./service/apache-proxy/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./service/apache-proxy/virtual-hosts/keycloak.conf:/usr/local/apache2/conf/sites/keycloak.conf:ro
      - ${PROXY_SSL_CERTIFICATE:-./client/ssl_cert/cert.crt}:/etc/ssl/cbio_https/cert.crt:ro
      - ${PROXY_SSL_KEY:-./client/ssl_cert/key.key}:/etc/ssl/cbio_https/key.key:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - xnat
```

**Comment by rherrick** [comment] 2020-06-23 20:11
That's caused by a discrepancy in the system time between the server and the browser. The SESSION_EXPIRATION_TIME cookie is set on each response by the server. The session timer on the XNAT page compares its current time to the time set by the server and, if the timer's current time is after the time set by the server, it pops up that message and redirects to the login page.

The question then becomes why your XNAT container seems to have a different time setting from your browser. Try looking at the Network panel in your browser's developer tools. On the response from the server, you should see the SESSION_EXPIRATION_TIME cookie set. It'll look something like this:

`SESSION_EXPIRATION_TIME=1592941865339,900000`

You can convert that on a site like [timestamp.online](https://timestamp.online), but disregard the ",900000" part and truncate the actual timestamp to 10 digits, so the value above becomes `1592941865`, which converts to 6/23/2020, 2:51:05 PM. You can see what time your browser thinks it is by typing this in the console:

```
> Date.now()
< 1592942619702
```

Same thing to convert it to a readable date, truncate to 10 digits.

For the other issues:

* #28 is fixed in the latest commit on the [**master** branch](https://github.com/NrgXnat/xnat-docker-compose/tree/master)
* The **nginx** issue isn't really an issue with this docker-compose project, but I'd guess with _any_ Docker or docker-compose configuration that tries to publish something to port 80. Either something is already using port 80 or some security configuration (selinux is often a culprit) prevents the container from using that port.

**Comment by pvannierop** [comment] 2020-06-24 05:41
@rherrick Thank you for looking at my problem. Indeed the `SESSION_EXPIRATION_TIME` appears to be the cause. In my case the expiration time is exactly the time of the request. With each refresh of the page this value is updated. Because the expiration time is the time of the request, the session never is established. To me this seems like a faulty/unset configuration option that determines session duration (defaults to zero length).

>The nginx issue isn't really an issue with this docker-compose project, but I'd guess with any Docker or docker-compose configuration that tries to publish something to port 80. Either something is already using port 80 or some security configuration (selinux is often a culprit) prevents the container from using that port.

I do not think this is the problem. I run apache proxy on port 80 without any problem on my system (see config in my original post). The nginx service in your docker-compose.yml does not start on the same port. Moreover, init of nginx proxy does not complain about port 80 already being occupied, which normally happens in such cases. I suspect the cause is different from what you propose.

**Comment by rherrick** [comment] 2020-06-24 21:01
> To me this seems like a faulty/unset configuration option that determines session duration (defaults to zero length).

The default session duration is 15 minutes. You can find out what it's set to for your deployment with the following query:

```
xnat=> SELECT value FROM xhbm_preference WHERE name = 'sessionTimeout';
   value
------------
 15 minutes
(1 row)
```

You can expand that to check the server time and calculated expiration time like this:

```
xnat=> SELECT now(), value, now() + value::INTERVAL AS expiry FROM xhbm_preference WHERE name = 'sessionTimeout';
              now              |   value    |            expiry
-------------------------------+------------+-------------------------------
 2020-06-24 17:15:23.271106+00 | 15 minutes | 2020-06-24 17:30:23.271106+00
(1 row)
```

If the value there isn't 15 minutes, you can either drop the database and restart the system (if you don't already have data in there that you want to preserve, at least) or change the value in the database directly (you _may_ need to restart for that to take effect due to caching).

I'm not sure what you mean by this:

> The nginx service in your docker-compose.yml does not start on the same port.

It's only on port 80. Are you referring to something else?

Anyway, I suspect the problem is related to this:

> The XNAT service is built with TOMCAT_XNAT_FOLDER set to xnat to support the https://localhost/xnat URL pattern.

[**nginx/nginx.conf**](https://github.com/NrgXnat/xnat-docker-compose/blob/master/nginx/nginx.conf) proxies requests from the top-level context:

```
server {
  listen 80;
  location / {
    proxy_pass                          http://xnat-web:8080;
    proxy_redirect                      http://xnat-web:8080 $scheme://localhost;
```

I don't think that should be an issue: http://server/xnat should match just fine, but that's the only thing I can see that could complicate what's really a pretty simple configuration.

A couple things you can try:

- Run nginx in debug mode, as described on the [nginx container page](https://hub.docker.com/_/nginx). Look for the section **Running nginx in debug mode**.
- Log into the nginx container and try calling to xnat-web from there:

```
$ docker exec --interactive --tty xnat-docker-compose_xnat-nginx_1 sh
/ # wget -O - http://xnat-web:8080
<bunch of stuff>
-                    100% |***************************************************************************************************************************************| 18624   0:00:00 ETA
```

**Closed by rherrick** 2020-06-24 21:01 UTC

**Comment by pvannierop** [comment] 2020-06-25 06:01
@rherrick Thank you for your suggestions. The database appears ok, but the problem persists. I did the following:
- stop all docker services
- delete the postgress data directory
- delete the xnat application directory
- restart all docker services

The xnat service report that the database is rebuilt:

```
SOURCE: /usr/local/tomcat/webapps/xnat/
===========================
New Database -- BEGINNING Initialization
===========================
===========================
Database initialization complete.
===========================
```

And Tomcat reports correct startup of the server:

```
Jun 25, 2020 5:40:44 AM org.apache.catalina.startup.Catalina start
INFO: Server startup in 111840 ms
```

After this I checked the database contents. This seems to be correct:

```
xnat=> SELECT * FROM xhbm_preference WHERE name = 'sessionTimeout';
 id |         created         |      disabled       | enabled |        timestamp        | entity_id |      name      | scope |   value    | tool 
----+-------------------------+---------------------+---------+-------------------------+-----------+----------------+-------+------------+------
 90 | 2020-06-25 05:54:29.149 | 1970-01-01 00:00:00 | t       | 2020-06-25 05:54:29.149 |           | sessionTimeout |     0 | 15 minutes |    2
(1 row)
```

But as mentioned the problem persists:
![image](https://user-images.githubusercontent.com/745885/85663796-ccd5f380-b6b9-11ea-9423-c4d93d517614.png)

It is interesting to see that the page that I arrive at is different from the first attemps, but that the underlying problem has not been resolved.
